package dev.mizarc.bellclaims.domain.values

enum class WorldActionType {
    FIRE_BURN,
    FIRE_SPREAD,
    MOB_DESTROY_BLOCK,
    MOB_DAMAGE_ENTITY,
    ENTITY_EXPLOSION_DESTROY_BLOCK,
    ENTITY_EXPLOSION_DAMAGE_ENTITY,
    BLOCK_EXPLOSION_DESTROY_BLOCK,
    BLOCK_EXPLOSION_DAMAGE_ENTITY,
    PISTON_EXTEND,
    PISTON_RETRACT,
    FLUID_FLOW,
    FLUID_FORM_BLOCK,
    TREE_GROWTH,
    SPREAD,
    DISPENSE,
    FLUID_ABSORB,
    LIGHTNING_DAMAGE,
    FALLING_BLOCK_MATERIALISE,
    ANIMAL_ENTER_VEHICLE
}